spring:
  application:
    name: codefreelaapi
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://${URL_BD}/codefreeladb
    username: ${USERNAME_BD}
    password: ${PASSWORD_BD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  override-with-generic-response: false

jwt:
  secret: ${JWT_SECRET}